import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`max-w-screen-sm mx-auto bg-gray-800 ${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}

        <div className="fixed bottom-0 left-0 flex w-full justify-around bg-blue-500 py-2 text-white">
          <a className="grid justify-items-center gap-0.5 p-2 text-lg font-medium transition-opacity opacity-100 hover:bg-gray-100 rounded-full" href="/">
            <span className="grid h-9 w-12 place-content-center rounded-full transition-colors bg-primary/[0.08]">
              <img alt="icon" loading="lazy" width="25" height="25" decoding="async" data-nimg="1" src="/navlink/home-icon.svg" />
            </span>
            <span>Home</span>
          </a>
        </div>
      </body>
    </html>
  );
}
